### ISSUE TITLE
npm test should work without global deps

### ISSUE THREAD

**Issue by steida** [bradharms/redux-inject#1]
Btw, I am happy someone finally created Este like deps middleware https://github.com/este/este/blob/e644cd46d74771bd39128a90a5808710a2a8019e/src/common/lib/injectDependencies.js

**Comment by bradharms** [comment]
I have never used Este. I wasn't aware it had a similar middleware.

**Comment by bradharms** [comment]
As for the issue, I agree. If I can figure out how to make jasmine and karma work without the global executables then I will implement this.

**Comment by bradharms** [comment]
Although, karma is using PhantomJS currently. That is a binary executable and I don't know if I can make it run from just node_mouldes. I may need to remove the dependency on Phantom if I want to make the tests work without globals.
