### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by steida** [bradharms/redux-inject#3]
What do you think about this implementation? I suppose it's more practical since we don't need thunk.

https://github.com/este/este/blob/a2d497c3e3951b85751807789a7f80ee170ce32b/src/common/configureStore.js#L24

**Comment by bradharms** [comment]
I thought about combining the functionality of redux-thunk with injection into a single lib, just for the sake of simplicity. However ultimately I decided I like the fact that we have a middleware that is focused purely on thunks without doing anything extra, and I wanted redux-inject to have that same kind of focus. That way dependencies and thunks can remain logically separated. Not that a combination library wouldn't be useful. I'll keep it under consideration.
