### ISSUE TITLE
Redux-thunk provides withExtraArgument for this very thing.

### ISSUE THREAD

**Issue by ngbrown** [bradharms/redux-inject#5]
React-thunk supports passing an arbitrary object to a thunk using [withExtraArgument](https://github.com/gaearon/redux-thunk#injecting-a-custom-argument).

You might consider making a note in the README that injection is natively supported by Redux-thunk.

**Comment by bradharms** [comment]
Thanks. I added a note in the "Use with Redux Thunk" section.
